# Generated by Django 4.2.2 on 2023-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/profiles/default.jpg', null=True, upload_to='uploads/profiles/%Y/%m/', verbose_name='аватар'),
        ),
    ]
