# Generated by Django 4.2.2 on 2023-06-30 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='category')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='topic')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='topic')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(default='Other', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('fromplace', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(default='DefaultUser', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.profile')),
                ('category', models.ForeignKey(default='Other', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.category')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.status')),
                ('topic', models.ForeignKey(default='Other', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.topic')),
            ],
            options={
                'verbose_name': 'Надпись',
                'verbose_name_plural': 'Надписи',
                'ordering': ['-published'],
            },
        ),
    ]
